# Use the official OpenJDK image as the base image
FROM adoptopenjdk:11-jdk-hotspot

# Set the working directory
WORKDIR /app

# Compile the Java code
COPY backend/src ./src
COPY backend/build.gradle .
COPY backend/gradlew .
COPY backend/gradle ./gradle
RUN ./gradlew build


# Copy the Spring Boot application JAR file to the container
COPY backend/build/libs/*.jar application-0.0.1-SNAPSHOT.jar

# Expose the port on which Spring Boot application runs
EXPOSE 8080

# Command to run the Spring Boot application
CMD ["java", "-jar", "application-0.0.1-SNAPSHOT.jar"]
