# Use the official OpenJDK image as the base image
FROM adoptopenjdk:11-jdk-hotspot

# Set the working directory
WORKDIR /app

# Compile the Java code
COPY Backend/src ./src
COPY Backend/build.gradle .
COPY Backend/gradlew .
COPY Backend/gradle ./gradle
RUN ./gradlew build


# Copy the Spring Boot application JAR file to the container
COPY Backend/build/libs/*.jar my-app.jar

# Expose the port on which Spring Boot application runs
EXPOSE 80

# Command to run the Spring Boot application
CMD ["java", "-jar", "my-app.jar"]
