# Use the official Node.js image as the base image
FROM node:20 as build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY angular-frontend/package*.json ./

# Install Angular CLI and project dependencies
RUN npm install

# Copy the rest of the frontend source code to the container
COPY angular-frontend/ .

# Build the Angular application
RUN npm run build

# Copy the nginx cors configuration file to the container
COPY angular-frontend/cors.conf /etc/nginx/conf.d/default.conf

# Use a lightweight HTTP server to serve the Angular app
FROM nginx:alpine
COPY --from=build /app/dist/frontend /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
